site_name: hobby-knowledge-base
repo_url: https://github.com/StarfallProjects/obsidian-netlify-monorepo
site_author: Starfall Projects
theme:
  name: material
markdown_extensions:
  - wikilinks
  - literate-nav
